### ISSUE TITLE
Firmware update instructions

### ISSUE THREAD

**Issue by jonnew** [open-ephys/commutator-docs#18]
Add a page with latest compiled firmware and instructions on how update the commutator with it.

**Comment by ChucklesOnGitHub** [comment]
@aacuevas gave me the following instructions to find out the commutator fw version. Is this the method that we are going to propose to users?

1. Find the COM port of the commutator
2. Download PuTTY from https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
3. Run putty.exe
4. Configure as follows:

![image](https://github.com/user-attachments/assets/c3827d23-cd14-44bb-97e3-d412b3369307)
![image](https://github.com/user-attachments/assets/8a49c18c-8cde-49be-bc9f-7b4fdc6d9b0c)

5. Run command {print:}
6. Inform the result of the operation

**Comment by jonnew** [comment]
I think we should probably use the Arduino serial monitor because that's going to be needed to update the firmware anyway (well not _needed_ but I think it's the fastest way)

1. Download the [Arduino IDE](https://www.arduino.cc/en/software)
1. Install it and open the program.
1. Go to File -> Preferences and add `https://www.pjrc.com/teensy/package_teensy_index.json` to the Additional Board Mangager URLs:
    ![image](https://github.com/user-attachments/assets/b0dafd5e-b495-48b2-8483-5504d3c08729)
1. Install Teensy board support int eh Board Manager tab of the IDE
   ![image](https://github.com/user-attachments/assets/eeda9af8-bc99-40fb-988a-ea03267532a0)
1. Plug your commutator in and wait for the red light to stop flashing (charging internal battery, can take up to 30 seconds)
1. Select the Teensy from the Board dropdown menu
    ![image](https://github.com/user-attachments/assets/b024bd14-998d-44c9-8cd0-eba3723eb60f)
1. Go to Tools -> Serial Monitor to open a serial connection to the commutator
   ![image](https://github.com/user-attachments/assets/55263b36-0b57-4c7e-9ba1-05b0b20af221)
1. Type `{print:}` into the serial monitor prompt and press enter, this will tell you the firmware version of the commutator. Make sure to note the (1) Commutator type, (2) Firmware Version and (3) Teensy Type.
    ![image](https://github.com/user-attachments/assets/6a205bc3-7d65-456a-ac9d-3bad1836b3f2)
1. Open the [most recent firmware](https://github.com/open-ephys/commutators/blob/main/firmware/commutator/commutator.ino) in the IDE
1. Adjust the defintions at the top of the file to match your Teensy and commutator type (look at the results of the `{print:} command above
  ![image](https://github.com/user-attachments/assets/1c077e29-b3f8-4eaa-9415-6363d06cf20f)
1. Press the Upload Button to compile and flash the latest firmware. 
   ![image](https://github.com/user-attachments/assets/ad2341c6-9850-462c-9373-c54c161e3512)
1. Repeat step 8 to confirm the firmware has been updated:
   ![image](https://github.com/user-attachments/assets/fb969f9e-b360-408f-85db-828666f00951)

**Comment by bruno-f-cruz** [comment]
Heya,
A small piece of feedback after updating one of your commutators. The updating procedure itself is easy and didn't have any problem (I used the arduino IDE and followed the instructions in https://www.pjrc.com/teensy/td_download.html). However, one thing that did throw me off a bit were the defaults that the firmware ships with. It took me a while to realize why the `{print:}` command returned sensible information but the `turn` command did not drive any movement of the motor. Turns out I had to first set the RPMs and Acc parameters. For future people that go through this process (assuming that there is no reason to do otherwise?) I would suggest changing the defaults to something that can actually drive the motors after sending a `turn` command.

**Comment by ChucklesOnGitHub** [comment]
I think this content should expand the one already [here](https://open-ephys.github.io/commutator-docs/coax-commutator/developer-guide/index.html#teensy-and-programming-an-open-ephys-commutator), with an explicit command that can be used for testing. 

This might not require a separate Firmware update page, however, I would suggest we do keep the table such as [the ones here](https://open-ephys.github.io/onix-docs/Resources/downloads.html#downloads) with the firmware version and date of release, and separate for each hardware version.

fw v1.6 can be used on commutators with SN after 0124 - and will not work on others
fw v1.5 is needed on commutators with SN before 0124

SN: 7759**0124**zzzz (Jan 2024)

**Comment by ChucklesOnGitHub** [comment]
For users attempting to do it with the library versions out now, there is a compilation error because ArduinoJson 7 changed thins with respect to ArduinoJson 5.

Compilation error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/v7/upgrade-from-v5/ to learn how to upgrade to ArduinoJson 7

**Comment by jonnew** [comment]
They need to use the old library. They can select an old version in the arduino package manager

**Comment by ChucklesOnGitHub** [comment]
5.13.15 works

**Comment by ChucklesOnGitHub** [comment]
> fw v1.6 can be used on commutators with SN after 0124 (Teensy LC) - and will not work on others fw v1.5 is needed on commutators with SN before 0124 (Teensy 3.2)
> 
> SN: 7759**0124**zzzz (Jan 2024)
> we discussed providing users with the .hex used in production for ease of library management

Here they are until we can make this docs page properly:
[coaxial_commutator_firmware_hex.zip](https://github.com/user-attachments/files/17776505/coaxial_commutator_firmware_hex.zip)

I guess the original files used for v1.6 and v1.5.1 should be tagged as releases.

**Comment by ChucklesOnGitHub** [comment]
Adding the instructions for using the hex files. Hope to get this online soon.

1. Download the hex file that is in [the zip above](https://github.com/open-ephys/commutator-docs/issues/18#issuecomment-2478915407). Use the file for the commutator version you have.

2. Connect the commutator to USB and wait for the Status LED to stop blinking red. Try not to use a hub for this so the connection is reliable.

3. After selecting the board in the Arduino IDE, click verify on any sketch and you will see another window pop up, the Teensy Loader application:

![Image](https://github.com/user-attachments/assets/cd72c7bb-09a5-4653-95d7-f3e223937e7e)

4. In the Teensy Loader, go to File > Open HEX File

![Image](https://github.com/user-attachments/assets/e7755bd1-0782-4350-82af-cb8cfc2400a7)

5. Press the physical button on the side of the commutator to upload the firmware.

6. To test the upload, in the Arduino IDE, go to Tools -> Serial Monitor and type {print:} into the serial monitor prompt. Press enter and you should see the version of the commutator now matches what you uploaded.

7. You can test it works in Bonsai like explained [here](https://open-ephys.github.io/commutator-docs/coax-commutator/quick-start-guide/index.html#quick-start), before moving on to using sensor data to drive it with the AutoCommutator node. The button and indicator lights are explained [here](https://open-ephys.github.io/commutator-docs/coax-commutator/user-guide/status-led.html#).
